version: '3.8'
services:
  redis:
    image: 'bitnami/redis:latest'
    container_name: 'redis-cache'
    environment:
       - REDIS_PASSWORD=test123
       - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis'
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  default:
    driver: bridge
volumes:
  redis_data: 

  
