---
spring:
  config:
    activate:
      on-profile: demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ep-dry-fire-93265970.eu-central-1.aws.neon.tech:5432/neondb
    username: aminechaghir1999
    password: gwHBXGy9CJ1T
    hikari:
      maxLifeTime: 600000 #10 minutes wait time

  data:
    redis:
      host: localhost
      port: 6379
      password: test123
      database: 0
      timeout: 30000
      pool:
        maxIdle: 8
        minIdle: 0
        maxActive: -1
        maxWait: 30000
      repositories:
        enabled: true

#----------------------------------------

