---
spring:
  config:
    activate:
      on-profile: demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  data:
    redis:
      host: localhost
      port: 6379
      password: redisPassword.2023
      database: 0
      timeout: 30

#----------------------------------------

