---
spring:
  config:
    activate:
      on-profile: demo
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
#----------------------------------------

